In [74]:
import re
import pandas as pd

In [75]:
f=open('_chat.txt','r',encoding='utf-8')

In [76]:
data=f.read()

In [77]:
print(data)

[14/06/2025, 2:05:38 pm] MDS A (unofficial): ‎Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them.
[14/06/2025, 2:05:38 pm] ~ Serin Tomy: ‎~ Serin Tomy created this group
[14/06/2025, 3:29:13 pm] MDS A (unofficial): ‎You joined using a group link.
[14/06/2025, 4:14:21 pm] Tejaswini Christ: ‎~ Serin Tomy added Tejaswini Christ
[14/06/2025, 4:27:24 pm] MDS A (unofficial): ‎Tejaswini Christ added ~ Madhurai and ~ Vanshika
[14/06/2025, 4:33:10 pm] Mugunthan christ: ‎Mugunthan christ joined using a group link.
[14/06/2025, 4:36:58 pm] MDS A (unofficial): ‎~ Serin Tomy added Tall Girl Blue Kurta and ‪+91 95404 69516‬
[14/06/2025, 4:39:13 pm] ~ Preeti Kumari: ‎~ Serin Tomy added ~ Preeti Kumari
[14/06/2025, 4:39:48 pm] ~ Brunda Nagaraj: ‎~ Serin Tomy added ~ Brunda Nagaraj
[14/06/2025, 4:44:35 pm] MDS A (unofficial): ‎~ Serin Tomy added Fredrik Christ, ~ Abhilasha, and ~ Swathi
[14/06/2025, 4:45:37 pm] ~ Deva: ‎~ Serin Tomy added ~ Deva
[14/06/2025, 4:55:34 pm] MDS A (unofficial): ‎~ Serin Tomy added Abinesh Christ, Mehvir Christ, and 6 others. Tap to see all.
[14/06/2025, 5:12:24 pm] ~ Tula: ‎~ Tula joined using a group link.
[14/06/2025, 5:19:51 pm] ~ Spoorthi Nadig: ‎~ Serin Tomy added ~ Spoorthi Nadig
‎[14/06/2025, 6:28:13 pm] ~ Serin Tomy: Foundation syllabus.pdf • ‎4 pages ‎document omitted
[14/06/2025, 6:48:21 pm] Sanmitra Christ: Thanks 👍
[14/06/2025, 7:12:05 pm] ~ Kathir A: Thank you:)
[14/06/2025, 7:43:29 pm] ~ Agnibha: ‎~ Agnibha joined using a group link.
‎[16/06/2025, 12:07:07 pm] Sanmitra Christ: ‎image omitted
[16/06/2025, 9:53:10 pm] Raj Christ: Anyone have a link of google form for selection of the foundation course?
[16/06/2025, 9:54:00 pm] Abinesh Christ: https://docs.google.com/forms/d/e/1FAIpQLSfjlW72MpOl89XatgxVNDYGak8NKXtpritpePJAIH5esULyFg/viewform?pli=1
[16/06/2025, 10:15:13 pm] Sanmitra Christ: Does anyone know the class routine for tomorrow? The one in the KP does not have the elective classes...
[16/06/2025, 10:19:16 pm] ~ Deva: Didn't Laxmi ma'am say that we wont be starting the foundational courses until all of us have filled in the form? So regular timings?
[16/06/2025, 10:19:39 pm] ~ Deva: Unless we have even more orientations coming our way ‎<This message was edited>
[16/06/2025, 10:20:11 pm] Sanmitra Christ: Ok then I guess from 10 am
‎[17/06/2025, 12:51:14 pm] ~ Swathi: ‎image omitted
[17/06/2025, 12:59:49 pm] Tejaswini Christ:
‎[17/06/2025, 1:40:38 pm] Tejaswini Christ: ‎image omitted
‎[17/06/2025, 4:17:59 pm] Tejaswini Christ: ‎image omitted
[17/06/2025, 9:23:32 pm] ~ Preeti Kumari: does anyone have syllabus of 1 Trimester
[17/06/2025, 9:25:00 pm] Raj Christ: you can find it inside your kp
[17/06/2025, 9:25:24 pm] ~ Preeti Kumari: okay thanks
‎[18/06/2025, 11:12:46 am] ~ 🦇: MDS-AY 25-26 (1).docx.pdf • ‎87 pages ‎document omitted
[18/06/2025, 5:00:05 pm] ~ Kathir A: ‎Waiting for this message. This may take a while.
[18/06/2025, 6:46:22 pm] Vishwa Christ: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket




Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Vollyball (girls)






Badminton(girls and boys) ‎<This message was edited>
[18/06/2025, 6:46:42 pm] Vishwa Christ: If ur interested in sports give your details
[18/06/2025, 6:54:54 pm] Vishwa Christ: It’s not like u should be in state level or district level.

If u are interested be in a team to represent our department of datascience
[18/06/2025, 6:55:58 pm] Fredrik Christ: Isnt this for university team selection?
[18/06/2025, 6:57:27 pm] Vishwa Christ: Senior asked me to collect all the names for representing both university levels as well as department levels
[18/06/2025, 6:58:38 pm] Fredrik Christ: Ohh I dont wanna be in university team, if there is interdepartment matches then I am in
[18/06/2025, 6:58:47 pm] Vishwa Christ: Which sport ‎<This message was edited>
[18/06/2025, 6:59:02 pm] Vishwa Christ: Edit in the above message
[18/06/2025, 7:00:09 pm] ~ Rohil Sudhakar: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Vollyball (girls)






Badminton(girls and boys)
[18/06/2025, 7:26:07 pm] ~ Varkey: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308



Vollyball (girls)






Badminton(girls and boys)
[18/06/2025, 7:28:50 pm] ~ Spoorthi Nadig: ‎This message was deleted.
[18/06/2025, 7:35:02 pm] Vishwa Christ: Mention badminton girls and type ur name
[18/06/2025, 7:50:14 pm] ~ Spoorthi Nadig: Badminton girls
Spoorthi KS nadig
2548334
7204667785
[18/06/2025, 7:53:42 pm] ~ Varkey: ‎This message was deleted.
[18/06/2025, 7:58:19 pm] ~ Brunda Nagaraj: Badminton girls
Brunda N
2548306
8296626676
[18/06/2025, 8:00:03 pm] ~ Varkey: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308



Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676
[18/06/2025, 8:42:09 pm] ~ Jay Surya: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405



Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405
[18/06/2025, 8:45:27 pm] Raj Christ: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)









Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079


Throw ball(Girls)






Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405



Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405
[18/06/2025, 11:59:58 pm] ~ Mariya: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079








Basketball (boys)







Basketball (Girls)





Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405


Throw ball(Girls)
Mariya K Joby
MDS A
2548323
9539367725 ‎<This message was edited>
[19/06/2025, 11:21:40 am] Tall Girl Blue Kurta: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079








Basketball (boys)







Basketball (Girls)
T Monika Shree
1 MDS A
2548337
9739396343




Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405


Throw ball(Girls)
Mariya K Joby
MDS A
2548323
9539367725
[19/06/2025, 3:03:13 pm] ~ Vanshika: Linux is in 213
‎[19/06/2025, 4:51:13 pm] ~ Brunda Nagaraj: ‎image omitted
[19/06/2025, 9:08:47 pm] Abinesh Christ: Dear all,
The cost of the formal uniform is ₹3000. The payment can be made either through bank transfer or in cash — the mode of payment will be confirmed and shared with you shortly.

We are also have an ATM facility in our campus, so in case cash payment is required, CRs can withdraw the amount easily. The exact process will be communicated soon, so there is no need to worry.

Feel free to reach out to me if anyone has any doubts or concerns regarding the payment.

Thank you.
[19/06/2025, 9:35:43 pm] ~ Kathir A: Sure thing 👍
[20/06/2025, 11:02:02 am] ~ Vanshika: All of you assemble at 10.55 am at upper basement, nexus commons for this program. We will start the peer learning from next week. 3rd hour placement orientation.
[20/06/2025, 11:04:56 am] ~ Vanshika: Please assemble asap
[20/06/2025, 11:58:42 am] ~ Jay Surya: @⁨~Vanshika⁩ hey some of us didn’t get the attendance sheet for the yoga thing
[20/06/2025, 12:00:18 pm] Raj Christ: @⁨~Vanshika⁩ Can you add our name in that sheet ?
[20/06/2025, 12:01:02 pm] ~ Vanshika: You guys need to sign on the sheet though
[20/06/2025, 12:01:35 pm] ~ Jay Surya: Can you bring it to the seminar hall so we can sign it
[20/06/2025, 12:01:46 pm] Abinesh Christ: Send your roll no
[20/06/2025, 12:02:04 pm] Abinesh Christ: For who didn't sign with your name
[20/06/2025, 12:02:29 pm] ~ Jay Surya: 11
[20/06/2025, 12:02:31 pm] Raj Christ: 325 and 309
[20/06/2025, 6:04:21 pm] Abinesh Christ: Anyone interested to be SDG Cr
We need two members from our class ??
[20/06/2025, 6:05:09 pm] Vishwa Christ: Vishwa Karthick S
2548342
[20/06/2025, 6:05:26 pm] ~ Shivani Hebbar: Yes
Shivani Hebbar
[20/06/2025, 6:08:06 pm] Abinesh Christ: Can you share your roll no
[20/06/2025, 6:08:45 pm] ~ Shivani Hebbar: Yes it’s 2548330
‎[20/06/2025, 11:48:02 pm] ~ Vanshika: Come all, as ONE‼️

Don’t miss out on the most awaited and effusive welcome event hosted by the Student Welfare Office (SWO) to charge your talent on stage, and mark your thrill upfront!🎬
The *Freshers Starhunt 2025* is a class-wise talent showdown, where each class takes the spotlight to perform, compete, and cheer their hearts out. You’re highly encouraged to show up in full spirit for your class because your presence counts just as much as your performance! 🌟

Date: 25th-27th June
Venue: Nexus Commons

Freshers Starhunt 2025 is here to orchestrate your show, and you wouldn’t want to miss out on this. Redefine your presence on stage and make every single beat count!💃🏼💥 ‎image omitted
[21/06/2025, 6:23:29 pm] Raj Christ: ‎This message was deleted.
[21/06/2025, 6:23:29 pm] Raj Christ: ‎This message was deleted.
[21/06/2025, 7:37:45 pm] ~ Varkey: What's this?
[21/06/2025, 7:40:25 pm] Raj Christ: Ignore it
[21/06/2025, 7:42:24 pm] ~ Varkey: Wym ignore da.. explain
[21/06/2025, 7:45:09 pm] Raj Christ: Bro its not for you this is for my office mates i just send it to wrong group
That's all 😅
[21/06/2025, 7:45:21 pm] ~ Varkey: Ohh oke💀
[21/06/2025, 8:06:19 pm] ~ Vanshika: Guyss please start preparing for the freshers star hunt, it'll be a lot of fun and it's a great way for y'all to interact and make friends here. We have points just for participating as well so show up for your class!!
[21/06/2025, 8:07:45 pm] ~ Vanshika: Y'all can send whatever you're interested in doing on this group and make teams ‼️
[21/06/2025, 9:16:38 pm] ~ Tula: ‎POLL:
Do not ignore
‎OPTION: Dance (15 votes)
‎OPTION: Song (6 votes)
‎OPTION: Theatre (1 vote)
‎OPTION: Not interested (4 votes)
[23/06/2025, 9:38:14 am] ~ Vanshika: 11 to 12 library orientation for MDS, seminar hall 6th Floor, B block,
12 to 1 , gender specific and skill orientation in same hall
[23/06/2025, 9:58:14 am] ~ Vanshika: Hello is there anyone who is not buying uniform from college?
[23/06/2025, 9:58:22 am] ~ Vanshika: Please react to this message
[23/06/2025, 11:04:44 am] ~ Vanshika: ❗IMPORTANT NOTICE – AUDIO SUBMISSION FOR STARHUNT❗

All participants are strictly instructed to *submit their audio entries in MP3 or WAV format only.* *YouTube video links will not be accepted under any circumstances.*

Ensure your audio file is properly labeled with your Class and section before submission.

 Deadline for submission is today by 5:00 PM Today
Late submissions will not be entertained.

Please take this seriously and adhere to the guidelines.

Thank you
Nupoor Muley
Stage Commitee
[23/06/2025, 1:59:20 pm] Tejaswini Christ: ‎Tejaswini Christ changed the group name to “1 MDS A (unofficial)”
[23/06/2025, 2:00:00 pm] ~ Vanshika: Hellooo
[23/06/2025, 2:00:13 pm] ~ Vanshika: ‼️The deadline to submit song is 5 pm today ‼️
[23/06/2025, 2:04:11 pm] ~ Vanshika: Since we have most votes for dance, we'll be doing a dance performance and make the WhatsApp group today
[23/06/2025, 2:04:32 pm] ~ Vanshika: Whoever wants to participate please react to this message
‎[23/06/2025, 4:21:29 pm] ~ Vanshika: ‎audio omitted
[23/06/2025, 4:21:32 pm] ~ Vanshika: here's the audio track, we'll begin practice from tomorrow
[23/06/2025, 4:23:06 pm] ~ Vanshika: @⁨Fredrik Christ⁩
[24/06/2025, 1:31:35 pm] ~ Vanshika: Does anyone have a speaker that we can use for dance practice?
[24/06/2025, 1:46:46 pm] ~ Preeti Kumari: ‎Open this link to join my WhatsApp Group: https://chat.whatsapp.com/IMw5ZW30fc55UUd2jKDr49
[24/06/2025, 1:47:27 pm] ~ Preeti Kumari: Students who have opted for the foundation of statistics
Kindly join this group
[24/06/2025, 2:48:24 pm] ~ Vanshika: ‼️‼️please stay back in the basement after 4 ‼️‼️
[24/06/2025, 4:20:01 pm] ~ Kathir A: I am here in the basement
[24/06/2025, 4:20:14 pm] ~ Kathir A: 4 of us here
[24/06/2025, 4:20:23 pm] ~ Vanshika: We'll be there soon
[24/06/2025, 4:32:07 pm] ~ Swathi: ‎This message was deleted.
[24/06/2025, 4:43:47 pm] Tejaswini Christ: We are here where are you folks ?
[24/06/2025, 4:44:32 pm] ~ Madhurai: A block
[24/06/2025, 4:44:38 pm] ~ Madhurai: basement
[24/06/2025, 4:44:49 pm] Tejaswini Christ: Hein
‎[24/06/2025, 5:28:42 pm] Tejaswini Christ: ‎video omitted
[24/06/2025, 5:54:31 pm] Tejaswini Christ: Guys I am out of the dance group
[24/06/2025, 5:57:46 pm] Abinesh Christ: ABHILASHA YADAV
BRUNDA N
SANMITRA BHATTACHARYA
SOWMYA N
T MONIKA SHREE
TEJASWINI KAILAS FULPAGARE

Unpaid list‼️
Pay asap before tonight.
[24/06/2025, 7:15:09 pm] Sanmitra Christ: Paid to Vanshika
[24/06/2025, 8:41:24 pm] ~ Vanshika: Does anyone have those assessment questions for hed tomorrow?
‎[24/06/2025, 8:42:24 pm] Fredrik Christ: ‎image omitted
‎[24/06/2025, 8:42:32 pm] Vishwa Christ: ‎image omitted
[24/06/2025, 8:42:36 pm] ~ Vanshika: Thank youu
[24/06/2025, 8:43:02 pm] Fredrik Christ: Okay this is better🙈
[25/06/2025, 10:56:00 am] Abinesh Christ: Good morning all,
12-1 we have orientation in A block second floor seminar hall, all should be there before 5 mins.
[25/06/2025, 7:31:45 pm] Abinesh Christ: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079








Basketball (boys)







Basketball (Girls)
T Monika Shree
1 MDS A
2548337
9739396343




Football (boys)






Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405


Throw ball(Girls)
Mariya K Joby
MDS A
2548323
9539367725
[25/06/2025, 7:32:20 pm] Abinesh Christ: They needed more players for playing kabaddi and thug of war tooo
[25/06/2025, 7:33:13 pm] Abinesh Christ: No prior certificate is needed... Just to play good is enough..
[25/06/2025, 7:33:34 pm] ~ Varkey: What if I can't play good💀
[25/06/2025, 7:33:40 pm] Abinesh Christ: They were expecting more members from our class kindly cooperate‼️‼️ ‎<This message was edited>
[25/06/2025, 7:34:05 pm] Fredrik Christ: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079








Basketball (boys)







Basketball (Girls)
T Monika Shree
1 MDS A
2548337
9739396343




Football (boys)
Fredrik Roshan B
1 MDS A
2548312
7259559226





Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405


Throw ball(Girls)
Mariya K Joby
MDS A
2548323
9539367725
[25/06/2025, 7:34:30 pm] Abinesh Christ: You can give your name bro they will decide IDK..
[25/06/2025, 7:34:41 pm] ~ Varkey: Oke
[25/06/2025, 7:37:22 pm] ~ Leju: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Leju Monachan
MDS A
8943162331


Table tennis

Vishwa Karthick S
MDS A 2548342
8825906079








Basketball (boys)







Basketball (Girls)
T Monika Shree
1 MDS A
2548337
9739396343




Football (boys)
Fredrik Roshan B
1 MDS A
2548312
7259559226





Football (girls)




Vollyball(boys)

Abinesh S
MDS A 2548302
8838503127


Varkey Francis
MDS A 2548336
8592965308


Jaya Surya D
MDS A  2548311
8520875405

Raj pansara
MDS A 2548325
7572806050

Vollyball (girls)






Badminton(girls and boys)

Spoorthi KS nadig
MDS A 2548334
7204667785


Brunda N
MDS A  2548306
8296626676


Jaya Surya D
MDS A  2548311
8520875405


Throw ball(Girls)
Mariya K Joby
MDS A
2548323
9539367725
[25/06/2025, 7:43:25 pm] Tall Girl Blue Kurta: Give name,class, batch,reg.no, ph.no

Kabbadi(boys)






Kabbadi(girls)










Cricket
Rohil Sudhakar
1 MDS A
2548327
6238001702

Raj pansara
MDS A 2548325
7572806050

Leju Monachan
MDS A
8943162331



In [78]:
pattern='\[\d{2}/\d{2}/\d{4}, \d{2}:\d{2}:\d{2}\s?[ap]m\] ~'

In [79]:
messages=re.split(pattern,data)[1:]
len(messages)

336

In [80]:
dates=re.findall(pattern,data)
len(dates)

336

In [81]:
from datetime import datetime

In [82]:
df=pd.DataFrame({'user_message':messages,'message_date':dates})

In [83]:
#convert message_date type
df['message_date'] = (
    df['message_date']
    .str.replace(r'[\[\]~]', '', regex=True)
    .str.replace('\u202f', ' ')
    .str.strip()
)

df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%Y, %I:%M:%S %p',
    errors='coerce'
)

In [84]:
df.rename(columns={'message_date':'date'},inplace=True)

df.head()

                                        user_message                date
0   Deva: Didn't Laxmi ma'am say that we wont be ... 2025-06-16 22:19:16
1   Deva: Unless we have even more orientations c... 2025-06-16 22:19:39
2   Swathi: ‎image omitted\n[17/06/2025, 12:59:49... 2025-06-17 12:51:14
3   🦇: MDS-AY 25-26 (1).docx.pdf • ‎87 pages ‎doc... 2025-06-18 11:12:46
4   Mariya: Give name,class, batch,reg.no, ph.no\... 2025-06-18 23:59:58

In [85]:
df.shape

(336, 2)

In [86]:
#separate users and messages

users=[]
messages=[]
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s',message)
    if entry[1:]:#user name
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notifications')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'],inplace=True)

df.head(10)

,date,user,message
0,2025-06-16 22:19:16,Deva,Didn't Laxmi ma'am say that we wont be startin...
1,2025-06-16 22:19:39,Deva,
2,2025-06-17 12:51:14,Swathi,
3,2025-06-18 11:12:46,🦇,
4,2025-06-18 23:59:58,Mariya,
5,2025-06-20 11:02:02,Vanshika,All of you assemble at 10.55 am at upper basem...
6,2025-06-20 11:04:56,Vanshika,Please assemble asap\n
7,2025-06-20 11:58:42,Jay Surya,
8,2025-06-20 12:01:02,Vanshika,You guys need to sign on the sheet though\n
9,2025-06-20 12:01:35,Jay Surya,

In [87]:
df['year']=df['date'].dt.year

In [88]:
df.head()

,date,user,message,year
0,2025-06-16 22:19:16,Deva,Didn't Laxmi ma'am say that we wont be startin...,2025
1,2025-06-16 22:19:39,Deva,,2025
2,2025-06-17 12:51:14,Swathi,,2025
3,2025-06-18 11:12:46,🦇,,2025
4,2025-06-18 23:59:58,Mariya,,2025

In [89]:
df['month']=df['date'].dt.month_name()

In [90]:
df['day'] = df['date'].dt.day

In [91]:
df['hour']=df['date'].dt.hour

In [92]:
df['minute'] = df['date'].dt.minute

In [93]:
df.head()

,date,user,message,year,month,day,hour,minute
0,2025-06-16 22:19:16,Deva,Didn't Laxmi ma'am say that we wont be startin...,2025,June,16,22,19
1,2025-06-16 22:19:39,Deva,,2025,June,16,22,19
2,2025-06-17 12:51:14,Swathi,,2025,June,17,12,51
3,2025-06-18 11:12:46,🦇,,2025,June,18,11,12
4,2025-06-18 23:59:58,Mariya,,2025,June,18,23,59